<a href="https://colab.research.google.com/github/Saifullah785/Python_for_Data_Science/blob/main/Numpy_for_Data_Science/Class_01_numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# **Creating Numpy Arrays**

In [2]:
# np.array / vector

import numpy as np
a = np.array([2,4,5,6])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# 2D and 3D we can call it matrix

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# 3D array / tensor
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [5]:
# dtype
# np.array([1,2,3],dtype=float)
# np.array([0,2,3],dtype=bool)
np.array([0,2,3],dtype=complex)

array([0.+0.j, 2.+0.j, 3.+0.j])

In [6]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [8]:
# np.ones and np.zeros
# np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#np.random
np.random.random((3,4))*100

array([[16.63640446, 86.85301725, 98.90918022, 55.9094751 ],
       [60.21840107, 58.70932939, 18.68306633, 29.63012226],
       [95.17513196, 30.68537823,  6.29997049, 33.01561831]])

In [10]:
# np.linespace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
# np.identity
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Array Attributes**

In [12]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# ndim
a1.ndim

1

In [14]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# size
print(a2.size)

a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [16]:
# itemsize
a1.itemsize

8

In [17]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# **Changing Datatype**

In [18]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# **Array Operations**

In [19]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
#scalar operations

# arithmetic
a1 -2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [21]:
#relational

a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

#**Array Functions**

In [23]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1,axis=0)

array([ 8,  9, 10, 11])

In [25]:
# mean /median /std/ var

np.mean(a1,axis=1)

array([1.5, 5.5, 9.5])

In [26]:
# trigonometric functions
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [27]:
# dot product
a2 = np.arange

In [28]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)

np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [29]:
# log and exponents
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [30]:
# round/floor/cell
# np.round(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[67., 47., 80.],
       [50., 21., 94.]])

#**Indexing and slicing**

In [31]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a1[5:9]

array([5, 6, 7, 8])

In [34]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a2[0,1]

np.int64(1)

In [36]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a3[0,0,0]

np.int64(0)

In [38]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a1[2:6]

array([2, 3, 4, 5])

In [40]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a2[::1,::3]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [42]:
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [43]:
a2[:,1:2]

array([[1],
       [5],
       [9]])

In [44]:
a2[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [45]:
a2[1:0,1:3]

array([], shape=(0, 2), dtype=int64)

In [46]:
a2[1,::3]

array([4, 7])

In [47]:
a2[:,2]

array([ 2,  6, 10])

In [48]:
a2[0:,1:4]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [49]:
a2[::1,::3]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [50]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

### Iterating

In [51]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [54]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


### Reshaping

In [57]:
# reshape
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [58]:
# ravel
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

### Stacking

In [59]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [61]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [62]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [66]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [69]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]