<a href="https://colab.research.google.com/github/Saifullah785/Python_for_Data_Science/blob/main/Numpy_for_Data_Science/Class_03__numpy_Tricks_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**np.sort**

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np

a = np.random.randint(1,100,15)
a

array([34, 13, 14, 28, 64,  4, 69, 49, 72, 51, 83, 25, 31, 79, 38])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[79, 95, 14, 30],
       [89, 57, 32, 46],
       [40,  4, 52, 26],
       [19, 13, 73, 14],
       [ 7, 70,  6, 10],
       [98,  1, 85, 53]])

In [4]:
np.sort(b,axis=1)

array([[14, 30, 79, 95],
       [32, 46, 57, 89],
       [ 4, 26, 40, 52],
       [13, 14, 19, 73],
       [ 6,  7, 10, 70],
       [ 1, 53, 85, 98]])

In [5]:
np.sort(a)[::-1]

array([83, 79, 72, 69, 64, 51, 49, 38, 34, 31, 28, 25, 14, 13,  4])

#**np.append**

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# code
a

array([34, 13, 14, 28, 64,  4, 69, 49, 72, 51, 83, 25, 31, 79, 38])

In [7]:
np.append(a,200)

array([ 34,  13,  14,  28,  64,   4,  69,  49,  72,  51,  83,  25,  31,
        79,  38, 200])

In [8]:
b

array([[79, 95, 14, 30],
       [89, 57, 32, 46],
       [40,  4, 52, 26],
       [19, 13, 73, 14],
       [ 7, 70,  6, 10],
       [98,  1, 85, 53]])

In [15]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[79., 95., 14., 30.,  1.],
       [89., 57., 32., 46.,  1.],
       [40.,  4., 52., 26.,  1.],
       [19., 13., 73., 14.,  1.],
       [ 7., 70.,  6., 10.,  1.],
       [98.,  1., 85., 53.,  1.]])

#**np.concatenate**

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [16]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# **np.unique**

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [19]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [20]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#**np.expand_dims**

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [21]:
a.shape

(15,)

In [23]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [25]:
np.expand_dims(a,axis=1).shape

(15, 1)

#**np.where**

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [26]:
a

array([34, 13, 14, 28, 64,  4, 69, 49, 72, 51, 83, 25, 31, 79, 38])

In [27]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 4,  6,  8,  9, 10, 13]),)

In [28]:
#replace all values > 50 with 0
np.where(a>50,0,a)

array([34, 13, 14, 28,  0,  4,  0, 49,  0,  0,  0, 25, 31,  0, 38])

In [29]:
# replace all even values with 0
np.where(a%2==0,0,a)

array([ 0, 13,  0,  0,  0,  0, 69, 49,  0, 51, 83, 25, 31, 79,  0])

#**np.argmax**

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [30]:
# code
a


array([34, 13, 14, 28, 64,  4, 69, 49, 72, 51, 83, 25, 31, 79, 38])

In [31]:
np.argmax(a)

np.int64(10)

In [32]:
b

array([[79, 95, 14, 30],
       [89, 57, 32, 46],
       [40,  4, 52, 26],
       [19, 13, 73, 14],
       [ 7, 70,  6, 10],
       [98,  1, 85, 53]])

In [33]:
np.argmax(b,axis=0)

array([5, 0, 5, 5])

In [34]:
np.argmax(b,axis=1)

array([1, 0, 2, 2, 1, 0])

In [35]:
# np.argin
np.argmin(a)

np.int64(5)

#**np.cumsum**

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [36]:
a

array([34, 13, 14, 28, 64,  4, 69, 49, 72, 51, 83, 25, 31, 79, 38])

In [37]:
np.cumsum(a)

array([ 34,  47,  61,  89, 153, 157, 226, 275, 347, 398, 481, 506, 537,
       616, 654])

In [38]:
b

array([[79, 95, 14, 30],
       [89, 57, 32, 46],
       [40,  4, 52, 26],
       [19, 13, 73, 14],
       [ 7, 70,  6, 10],
       [98,  1, 85, 53]])

In [41]:
np.cumsum(b,axis=1)

array([[ 79, 174, 188, 218],
       [ 89, 146, 178, 224],
       [ 40,  44,  96, 122],
       [ 19,  32, 105, 119],
       [  7,  77,  83,  93],
       [ 98,  99, 184, 237]])

In [42]:
a

array([34, 13, 14, 28, 64,  4, 69, 49, 72, 51, 83, 25, 31, 79, 38])

In [43]:
np.cumprod(a)

array([                  34,                  442,                 6188,
                     173264,             11088896,             44355584,
                 3060535296,         149966229504,       10797568524288,
            550675994738688,    45706107563311104,  1142652689082777600,
       -1471254785852997632, -5548663640129503232, -7935033514116055040])

#**np.percentile**

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [44]:
a

array([34, 13, 14, 28, 64,  4, 69, 49, 72, 51, 83, 25, 31, 79, 38])

In [45]:
np.percentile(a,100)

np.float64(83.0)

In [47]:
np.percentile(a,75)

np.float64(66.5)

In [48]:
np.percentile(a,25)

np.float64(26.5)

In [46]:
np.median(a)

np.float64(38.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [49]:
# code
a

array([34, 13, 14, 28, 64,  4, 69, 49, 72, 51, 83, 25, 31, 79, 38])

In [50]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 2, 3, 1, 1, 2, 2, 1, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))