<a href="https://colab.research.google.com/github/Saifullah785/Python_for_Data_Science/blob/main/Numpy_for_Data_Science/Class_03__numpy_Tricks_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**np.sort**

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [68]:
# code
import numpy as np

a = np.random.randint(1,100,15)
a

array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [69]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[96, 49, 67, 73],
       [33, 98, 27, 69],
       [66, 57, 49,  3],
       [72, 38, 63, 56],
       [84, 77, 95, 15],
       [73, 51, 42, 61]])

In [70]:
np.sort(b,axis=1)

array([[49, 67, 73, 96],
       [27, 33, 69, 98],
       [ 3, 49, 57, 66],
       [38, 56, 63, 72],
       [15, 77, 84, 95],
       [42, 51, 61, 73]])

In [71]:
np.sort(a)[::-1]

array([98, 98, 97, 95, 90, 85, 75, 60, 54, 47, 46, 27, 20, 18, 14])

#**np.append**

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [72]:
# code
a

array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [73]:
np.append(a,200)

array([ 95,  18,  98,  97,  54,  98,  85,  14,  75,  90,  20,  47,  60,
        27,  46, 200])

In [74]:
b

array([[96, 49, 67, 73],
       [33, 98, 27, 69],
       [66, 57, 49,  3],
       [72, 38, 63, 56],
       [84, 77, 95, 15],
       [73, 51, 42, 61]])

In [75]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[96., 49., 67., 73.,  1.],
       [33., 98., 27., 69.,  1.],
       [66., 57., 49.,  3.,  1.],
       [72., 38., 63., 56.,  1.],
       [84., 77., 95., 15.,  1.],
       [73., 51., 42., 61.,  1.]])

#**np.concatenate**

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [76]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [77]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# **np.unique**

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [79]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [80]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#**np.expand_dims**

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [81]:
a.shape

(15,)

In [82]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [83]:
np.expand_dims(a,axis=1).shape

(15, 1)

#**np.where**

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [84]:
a

array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [85]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  3,  4,  5,  6,  8,  9, 12]),)

In [86]:
#replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0, 18,  0,  0,  0,  0,  0, 14,  0,  0, 20, 47,  0, 27, 46])

In [87]:
# replace all even values with 0
np.where(a%2==0,0,a)

array([95,  0,  0, 97,  0,  0, 85,  0, 75,  0,  0, 47,  0, 27,  0])

#**np.argmax**

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [88]:
# code
a


array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [89]:
np.argmax(a)

np.int64(2)

In [90]:
b

array([[96, 49, 67, 73],
       [33, 98, 27, 69],
       [66, 57, 49,  3],
       [72, 38, 63, 56],
       [84, 77, 95, 15],
       [73, 51, 42, 61]])

In [91]:
np.argmax(b,axis=0)

array([0, 1, 4, 0])

In [92]:
np.argmax(b,axis=1)

array([0, 1, 0, 0, 2, 0])

In [93]:
# np.argin
np.argmin(a)

np.int64(7)

#**np.cumsum**

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [94]:
a

array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [95]:
np.cumsum(a)

array([ 95, 113, 211, 308, 362, 460, 545, 559, 634, 724, 744, 791, 851,
       878, 924])

In [96]:
b

array([[96, 49, 67, 73],
       [33, 98, 27, 69],
       [66, 57, 49,  3],
       [72, 38, 63, 56],
       [84, 77, 95, 15],
       [73, 51, 42, 61]])

In [97]:
np.cumsum(b,axis=1)

array([[ 96, 145, 212, 285],
       [ 33, 131, 158, 227],
       [ 66, 123, 172, 175],
       [ 72, 110, 173, 229],
       [ 84, 161, 256, 271],
       [ 73, 124, 166, 227]])

In [98]:
a

array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [99]:
np.cumprod(a)

array([                  95,                 1710,               167580,
                   16255260,            877784040,          86022835920,
              7311941053200,      102367174744800,     7677538105860000,
         690978429527400000, -4627175483161551616,  3883681175921693440,
       -6786802402922564608,  1223775858186271744,   953457255439845376])

#**np.percentile**

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [100]:
a

array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [101]:
np.percentile(a,100)

np.float64(98.0)

In [102]:
np.percentile(a,75)

np.float64(92.5)

In [103]:
np.percentile(a,25)

np.float64(36.5)

In [104]:
np.median(a)

np.float64(60.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [105]:
# code
a

array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [106]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 2, 0, 2, 1, 1, 1, 1, 5]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

#**np.corrcoef**

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [107]:
# code
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

#**np.isin**

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [108]:
# code
a

array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [109]:
items = [10,20,30,40,50,60,70,80,90,100]


np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
        True,  True, False,  True, False, False])

In [110]:
a[np.isin(a,items)]

array([90, 20, 60])

#**np.flip**

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [111]:
# code
a

array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [112]:
np.flip(a)

array([46, 27, 60, 47, 20, 90, 75, 14, 85, 98, 54, 97, 98, 18, 95])

In [113]:
b

array([[96, 49, 67, 73],
       [33, 98, 27, 69],
       [66, 57, 49,  3],
       [72, 38, 63, 56],
       [84, 77, 95, 15],
       [73, 51, 42, 61]])

In [114]:
np.flip(b,axis=0)

array([[73, 51, 42, 61],
       [84, 77, 95, 15],
       [72, 38, 63, 56],
       [66, 57, 49,  3],
       [33, 98, 27, 69],
       [96, 49, 67, 73]])

#**np.put**

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [115]:
# code
a

array([95, 18, 98, 97, 54, 98, 85, 14, 75, 90, 20, 47, 60, 27, 46])

In [116]:
# code
np.put(a,[0,1],[110,530])

#**np.delete**

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [117]:
# code
a

array([110, 530,  98,  97,  54,  98,  85,  14,  75,  90,  20,  47,  60,
        27,  46])

In [118]:
# code
# np.delete(a,[0,1,2])
np.delete(a,0)

array([530,  98,  97,  54,  98,  85,  14,  75,  90,  20,  47,  60,  27,
        46])

#**Set functions**

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [119]:
# code
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [120]:
# code
np.intersect1d(m,n)

array([3, 4, 5])

In [121]:
# code
np.setdiff1d(m,n)

array([1, 2])

In [122]:
# code
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [123]:
# code
m[np.in1d(m,9)]

<ipython-input-123-f892b6e59cb5>:2: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,9)]


array([], dtype=int64)

#**np.clip**

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [124]:
# code
a

array([110, 530,  98,  97,  54,  98,  85,  14,  75,  90,  20,  47,  60,
        27,  46])

In [125]:
# code
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 54, 75, 75, 25, 75, 75, 25, 47, 60, 27, 46])

In [126]:
# 17. np.swapaxes

In [127]:
# 18. np.uniform

In [128]:
# 19. np.count_nonzero

In [129]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [130]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [131]:
# 25. np.allclose and equals